In [1]:
# 행렬분해, 경사하강법(딥러닝)을 이용한 알고리즘

# 행렬분해 - matrix를 두 개의 서로 다른 행렬로 분해하는 것
#           분해된 행렬은 원래 행렬의 내재된 다른 의미를 갖는 행렬로 변환됨

# 경사하강법 - 함수를 값을 최소화하는 파라미터들을 찾는 방식
#              f(x) = w1x1 + w2x2 + ... => f(x)를 최소화하는 w1, w2, ... 를 찾는 방법
#              f(x)를 w1으로 미분한 값을 w1에 더해서 업데이트
#              f(x)를 w2로 미분한 값을 w2에 더해서 업데이트

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# 경사하강법을 이용한 행렬분해

In [4]:
# 사용자 영화 평점 매트릭스

R = np.array(
[[4, np.nan, np.nan, 2, np.nan],
[np.nan, 5, np.nan, 3, 1],
[np.nan, np.nan, 3, 4, 4],
[5, 2, 1, 2, np.nan]])

R

array([[ 4., nan, nan,  2., nan],
       [nan,  5., nan,  3.,  1.],
       [nan, nan,  3.,  4.,  4.],
       [ 5.,  2.,  1.,  2., nan]])

In [10]:
num_users, num_items = R.shape

print(num_users, num_items)    # 이용자수, 영화수

4 5


In [11]:
k = 3

In [ ]:
# a * b = c : 
#     a의 row원소수, b의 칼럼 수가 같아야한다
#     c의 shape은 (a row num, b col num)

In [13]:
# R = P * Q.T

In [16]:
np.random.seed(1)

P = np.random.normal(scale = 1/k, size = (num_users, k))
Q = np.random.normal(scale = 1/k, size = (num_items, k))

In [69]:
from sklearn.metrics import mean_squared_error

def get_rmse(R, P, Q, non_zeros):
    full_pred_matrix = np.dot(P, Q.T) # 인위적으로 만든 matrix
    
    error = 0
    
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]  # 실제 matrix에서 값이 존재하는 index값, # non zero data 행 인덱스값
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]  # non zero data 열 인덱스값
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]   # 실제 행렬의 non zero data 실제값
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]  # 예상 행렬의 non zero data 실제값
    
    # 실제값(실제 matrix R)과 예측값(가상으로 만든 matrix full_predict_matrix)으로 mse를 계산
    # matrix엣의 mse를 계산
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)
    
    return rmse

In [70]:
non_zeros = [(i, j, R[i,j]) for i in range(num_users) for j in range(num_items) if R[i, j] > 0]

In [71]:
# 경사하강법

In [72]:
steps = 1000
learning_rate = 0.01
r_lambda = 0.01  # 규제값 크기

In [73]:
for step in range(steps):
    for i, j, r in non_zeros:     # 실제 행렬에서 값이 있는 인덱스, 칼럽, 값을 가져온다
        eij = r - np.dot(P[i, :], Q[j, :].T)    # P : 사용자행 벡터, Q : 아이템행 벡터, 실제값과 예상행렬의 값과의 차이
        P[i,:] = P[i, :] + learning_rate * (eij * Q[j, :] - r_lambda * P[i, :])
        Q[j,:] = Q[j, :] + learning_rate * (eij * P[i, :] - r_lambda * Q[j, :])
        
        rmse = get_rmse(R, P, Q, non_zeros)    # non_zeros - 원본행렬에서 0값이 아닌 위치인덱스와 값
        
        if(step % 50) == 0:
            print('steps :', step, 'rmse :', rmse)

steps : 0 rmse : 0.03536981683628636
steps : 0 rmse : 0.03527740737147378
steps : 0 rmse : 0.03519751104827775
steps : 0 rmse : 0.035210203647645696
steps : 0 rmse : 0.03525615745117445
steps : 0 rmse : 0.035167218540780615
steps : 0 rmse : 0.035136535623881915
steps : 0 rmse : 0.035150075283052536
steps : 0 rmse : 0.03487767973341188
steps : 0 rmse : 0.03492847068184313
steps : 0 rmse : 0.035007019437307337
steps : 0 rmse : 0.0351910285492646
steps : 50 rmse : 0.03188091024062512
steps : 50 rmse : 0.03180319616271724
steps : 50 rmse : 0.03171889312142398
steps : 50 rmse : 0.031725449801502485
steps : 50 rmse : 0.031777477160693714
steps : 50 rmse : 0.031694917106130115
steps : 50 rmse : 0.03165005129789624
steps : 50 rmse : 0.03166144952758559
steps : 50 rmse : 0.03138066653859928
steps : 50 rmse : 0.031434653016503965
steps : 50 rmse : 0.031525067181209336
steps : 50 rmse : 0.031722201392570336
steps : 100 rmse : 0.029158124166874713
steps : 100 rmse : 0.029095235325799825
steps : 10

steps : 950 rmse : 0.018927821664187786
steps : 950 rmse : 0.018974289273798822
steps : 950 rmse : 0.018858716673620334
steps : 950 rmse : 0.01881771899658715
steps : 950 rmse : 0.018914650813206133
steps : 950 rmse : 0.018881530746652126
steps : 950 rmse : 0.01874075495468232
steps : 950 rmse : 0.018731151372958263
steps : 950 rmse : 0.018425757342918674
steps : 950 rmse : 0.018507257487936073
steps : 950 rmse : 0.018630232054429714
steps : 950 rmse : 0.018870059677102924


In [74]:
pred_matrix = np.dot(P, Q.T)  # P 와 Q 가 업데이트 되었다.
print('예측 행렬:\n', np.round(pred_matrix, 3))

예측 행렬:
 [[3.993 2.369 0.884 1.998 1.426]
 [4.287 4.979 0.322 2.984 1.006]
 [9.573 3.08  2.978 3.977 3.986]
 [4.966 1.998 1.026 2.02  1.965]]


In [49]:
import pickle

In [50]:
with open('ratings_matrix.pickle', 'rb') as f:
    ratings_matrix = pickle.load(f)

In [75]:
def get_rmse(R, P, Q, non_zeros):
    error = 0
    full_pred_matrix = np.dot(P, Q.T)
    
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]  # 실제행렬값
    
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]  # 예축행렬값
      
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)
    
    return rmse

In [76]:
def matrix_factorization(R, K, steps=200, learning_rate=0.01, r_lambda = 0.01):
    
    num_users, num_items = R.shape
    
    P = np.random.normal(scale=1./K, size=(num_users, K))
    Q = np.random.normal(scale=1./K, size=(num_items, K))

    break_count = 0
       
    non_zeros = [ (i, j, R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j] > 0 ]
   
    for step in range(steps):
        for i, j, r in non_zeros:
            eij = r - np.dot(P[i, :], Q[j, :].T)
            P[i,:] = P[i,:] + learning_rate*(eij * Q[j, :] - r_lambda*P[i,:])
            Q[j,:] = Q[j,:] + learning_rate*(eij * P[i, :] - r_lambda*Q[j,:])
       
        rmse = get_rmse(R, P, Q, non_zeros)
        if (step % 10) == 0 :
            print("### iteration step : ", step," rmse : ", rmse)
            
    return P, Q

In [77]:
P, Q = matrix_factorization(ratings_matrix.values, K=50, steps=200, learning_rate=0.01, r_lambda = 0.01)
pred_matrix = np.dot(P, Q.T)

### iteration step :  0  rmse :  2.8729590523415185
### iteration step :  10  rmse :  0.7751689243422856
### iteration step :  20  rmse :  0.5537474877497137
### iteration step :  30  rmse :  0.40368881085111313
### iteration step :  40  rmse :  0.3189991155493651
### iteration step :  50  rmse :  0.2701146687360125
### iteration step :  60  rmse :  0.24005226968391416
### iteration step :  70  rmse :  0.22024721939838302
### iteration step :  80  rmse :  0.2063715181024185
### iteration step :  90  rmse :  0.19614894903723173
### iteration step :  100  rmse :  0.18831132373049958
### iteration step :  110  rmse :  0.18210906530821652
### iteration step :  120  rmse :  0.17707517982732157
### iteration step :  130  rmse :  0.17290508730011464
### iteration step :  140  rmse :  0.16939202628333708
### iteration step :  150  rmse :  0.1663906839118822
### iteration step :  160  rmse :  0.1637958563994298
### iteration step :  170  rmse :  0.16152943025595382
### iteration step :  180  rm

In [78]:
ratings_matrix.shape

(706, 6033)

In [79]:
pred_matrix.shape

(706, 6033)

In [82]:
ratings_pred_matrix = pd.DataFrame(pred_matrix, index = ratings_matrix.index, columns = ratings_matrix.columns)
ratings_pred_matrix.head()

title   'Round Midnight (1986)  'Til There Was You (1997)  'burbs, The (1989)  \
userId                                                                          
1                     3.555666                   2.159842            3.028817   
2                     4.042561                   2.427290            4.286435   
3                     3.711459                   2.154449            4.460065   
4                     3.064267                   1.797329            1.885467   
5                     3.880001                   2.251895            3.142835   

title   'night Mother (1986)  *batteries not included (1987)  \
userId                                                         
1                   3.901788                        3.377757   
2                   4.240135                        4.008166   
3                   3.929028                        3.237729   
4                   3.001823                        2.940077   
5                   4.033303                        3.671936   

title   ...And Justice for All (1979)  1-900 (06) (1994)  10 (1979)  \
userId                                                                
1                            3.911236           2.153347   2.639678   
2                            4.753625           2.325696   3.739063   
3                            3.846470           2.130991   3.004557   
4                            2.717085           1.226566   2.254631   
5                            3.695018           1.592028   3.269441   

title   10 Things I Hate About You (1999)  100 Girls (2000)  ...  \
userId                                                       ...   
1                                3.759682          3.224469  ...   
2                                3.167588          3.470914  ...   
3                                2.808339          3.354645  ...   
4                                2.153997          2.633270  ...   
5                                3.431756          3.490227  ...   

title   Zero de conduite (Zero for Conduct) (Zéro de conduite: Jeunes diables au collège) (1933)  \
userId                                                                                             
1                                                2.865701                                          
2                                                2.985829                                          
3                                                2.694811                                          
4                                                2.318292                                          
5                                                2.442626                                          

title   Zeus and Roxanne (1997)  \
userId                            
1                      1.822462   
2                      1.873201   
3                      1.708401   
4                      1.429370   
5                      1.843348   

title   Ziggy Stardust and the Spiders from Mars (1973)  Zoolander (2001)  \
userId                                                                      
1                                              1.626562          3.271546   
2                                              1.608128          3.619765   
3                                              1.480801          3.123194   
4                                              1.119984          3.523544   
5                                              1.459751          3.400892   

title   Zorro, the Gay Blade (1981)  Zulu (1964)  Zus & Zo (2001)  \
userId                                                              
1                          1.284278     3.817903         2.149276   
2                          1.297612     4.365120         2.367471   
3                          1.194588     4.739826         2.120213   
4                          1.044003     3.137157         1.231094   
5                          1.294543     4.127748         1.645492   

title   eXistenZ (1999)  xXx (2002)  

In [80]:
ratings_matrix.head()

title   'Round Midnight (1986)  'Til There Was You (1997)  'burbs, The (1989)  \
userId                                                                          
1                          NaN                        NaN                 NaN   
2                          NaN                        NaN                 NaN   
3                          NaN                        NaN                 NaN   
4                          NaN                        NaN                 NaN   
5                          NaN                        NaN                 NaN   

title   'night Mother (1986)  *batteries not included (1987)  \
userId                                                         
1                        NaN                             NaN   
2                        NaN                             NaN   
3                        NaN                             NaN   
4                        NaN                             NaN   
5                        NaN                             NaN   

title   ...And Justice for All (1979)  1-900 (06) (1994)  10 (1979)  \
userId                                                                
1                                 NaN                NaN        NaN   
2                                 NaN                NaN        NaN   
3                                 NaN                NaN        NaN   
4                                 NaN                NaN        NaN   
5                                 NaN                NaN        NaN   

title   10 Things I Hate About You (1999)  100 Girls (2000)  ...  \
userId                                                       ...   
1                                     NaN               NaN  ...   
2                                     NaN               NaN  ...   
3                                     NaN               NaN  ...   
4                                     NaN               NaN  ...   
5                                     NaN               NaN  ...   

title   Zero de conduite (Zero for Conduct) (Zéro de conduite: Jeunes diables au collège) (1933)  \
userId                                                                                             
1                                                     NaN                                          
2                                                     NaN                                          
3                                                     NaN                                          
4                                                     NaN                                          
5                                                     NaN                                          

title   Zeus and Roxanne (1997)  \
userId                            
1                           NaN   
2                           NaN   
3                           NaN   
4                           NaN   
5                           NaN   

title   Ziggy Stardust and the Spiders from Mars (1973)  Zoolander (2001)  \
userId                                                                      
1                                                   NaN               NaN   
2                                                   NaN               NaN   
3                                                   NaN               NaN   
4                                                   NaN               NaN   
5                                                   NaN               NaN   

title   Zorro, the Gay Blade (1981)  Zulu (1964)  Zus & Zo (2001)  \
userId                                                              
1                               NaN          NaN              NaN   
2                               NaN          NaN              NaN   
3                               NaN          NaN              NaN   
4                               NaN          NaN              NaN   
5                               NaN          NaN              NaN   

title   eXistenZ (1999)  xXx (2002)  

In [83]:
user_id = 9
top_n = 50

ratings_pred_matrix.loc[user_id].sort_values(ascending=False)[:top_n]

title
Monty Python and the Holy Grail (1975)                                            5.868125
Network (1976)                                                                    5.573849
Raising Arizona (1987)                                                            5.562702
Braveheart (1995)                                                                 5.481068
Unforgiven (1992)                                                                 5.480685
Maverick (1994)                                                                   5.462828
Shawshank Redemption, The (1994)                                                  5.453794
Boot, Das (Boat, The) (1981)                                                      5.420071
Matrix, The (1999)                                                                5.303379
Airplane! (1980)                                                                  5.231960
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    5.